const cities = [
    {
        id: 1,
        name: "Bilaspur",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "Chamba",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Hamirpur",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Kangra",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: "Kinnaur",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: "Kullu",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: "Lahaul and Spiti",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: "Mandi",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: "Shimla",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: "Sirmaur",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: "Solan",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: "Una",
        state_id: 9,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Maharashtra districts
    {
        id: 13,
        name: "Ahmednagar",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 14,
        name: "Akola",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 15,
        name: "Amravati",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 16,
        name: "Aurangabad",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 17,
        name: "Beed",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 18,
        name: "Bhandara",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 19,
        name: "Buldhana",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 20,
        name: "Chandrapur",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 21,
        name: "Dhule",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 22,
        name: "Gadchiroli",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 23,
        name: "Gondia",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 24,
        name: "Hingoli",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 25,
        name: "Jalgaon",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 26,
        name: "Jalna",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 27,
        name: "Kolhapur",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 28,
        name: "Latur",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 29,
        name: "Mumbai City",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 30,
        name: "Mumbai Suburban",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 31,
        name: "Nanded",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 32,
        name: "Nandurbar",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 33,
        name: "Nagpur",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 34,
        name: "Nashik",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 35,
        name: "Osmanabad",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 36,
        name: "Palghar",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 37,
        name: "Parbhani",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 38,
        name: "Pune",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 39,
        name: "Raigad",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 40,
        name: "Ratnagiri",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 41,
        name: "Sangli",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 42,
        name: "Satara",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 43,
        name: "Sindhudurg",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 44,
        name: "Solapur",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 45,
        name: "Thane",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 46,
        name: "Wardha",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 47,
        name: "Washim",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 48,
        name: "Yavatmal",
        state_id: 14,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    
    // Punjab districts
    {
        id: 49,
        name: "Amritsar",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 50,
        name: "Barnala",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 51,
        name: "Bathinda",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 52,
        name: "Faridkot",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 53,
        name: "Fatehgarh Sahib",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 54,
        name: "Fazilka",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 55,
        name: "Firozpur",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 56,
        name: "Gurdaspur",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 57,
        name: "Hoshiarpur",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 58,
        name: "Jalandhar",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 59,
        name: "Kapurthala",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 60,
        name: "Ludhiana",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 61,
        name: "Mansa",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 62,
        name: "Malerkotla",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 63,
        name: "Moga",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 64,
        name: "Pathankot",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 65,
        name: "Patiala",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 66,
        name: "Rupnagar",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 67,
        name: "Sahibzada Ajit Singh Nagar",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 68,
        name: "Sangrur",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 69,
        name: "Shahid Bhagat Singh Nagar",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 70,
        name: "Sri Muktsar Sahib",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 71,
        name: "Tarn Taran",
        state_id: 20,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Haryana districts
    {
        id: 72,
        name: "Ambala",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 73,
        name: "Bhiwani",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 74,
        name: "Charkhi Dadri",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 75,
        name: "Faridabad",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 76,
        name: "Fatehabad",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 77,
        name: "Gurgaon",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 78,
        name: "Hissar",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 79,
        name: "Jhajjar",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 80,
        name: "Jind",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 81,
        name: "Kaithal",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 82,
        name: "Karnal",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 83,
        name: "Kurukshetra",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 84,
        name: "Mahendragarh",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 85,
        name: "Nuh",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 86,
        name: "Palwal",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 87,
        name: "Panchkula",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 88,
        name: "Panipat",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 89,
        name: "Rewari",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 90,
        name: "Rohtak",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 91,
        name: "Sirsa",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 92,
        name: "Sonipat",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 93,
        name: "Yamuna Nagar",
        state_id: 8,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Uttarakhand districts
    {
        id: 94,
        name: "Almora",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 95,
        name: "Bageshwar",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 96,
        name: "Chamoli",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 97,
        name: "Champawat",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 98,
        name: "Dehradun",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 99,
        name: "Haridwar",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 100,
        name: "Nainital",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 101,
        name: "Pauri Garhwal",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 102,
        name: "Pithoragarh",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 103,
        name: "Rudraprayag",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 104,
        name: "Tehri Garhwal",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 105,
        name: "Udham Singh Nagar",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 106,
        name: "Uttarkashi",
        state_id: 27,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Rajasthan districts
    {
        id: 107,
        name: "Ajmer",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 108,
        name: "Alwar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 109,
        name: "Balotra",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 110,
        name: "Banswara",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 111,
        name: "Baran",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 112,
        name: "Barmer",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 113,
        name: "Beawar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 114,
        name: "Bharatpur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 115,
        name: "Bhilwara",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 116,
        name: "Bikaner",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 117,
        name: "Bundi",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 118,
        name: "Chittorgarh",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 119,
        name: "Churu",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 120,
        name: "Dausa",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 121,
        name: "Deeg",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 122,
        name: "Dholpur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 123,
        name: "Didwana-Kuchaman",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 124,
        name: "Dungarpur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 125,
        name: "Ganganagar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 126,
        name: "Hanumangarh",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 127,
        name: "Jaipur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 128,
        name: "Jaisalmer",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 129,
        name: "Jalore",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 130,
        name: "Jhalawar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 131,
        name: "Jhunjhunu",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 132,
        name: "Jodhpur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 133,
        name: "Karauli",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 134,
        name: "Khairthal-Tijara",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 135,
        name: "Kota",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 136,
        name: "Kotputli-Behror",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 137,
        name: "Nagaur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 138,
        name: "Pali",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 139,
        name: "Phalodi",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 140,
        name: "Pratapgarh",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 141,
        name: "Rajsamand",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 142,
        name: "Salumbar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 143,
        name: "Sawai Madhopur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 144,
        name: "Sikar",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 145,
        name: "Sirohi",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 146,
        name: "Tonk",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 147,
        name: "Udaipur",
        state_id: 21,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    // Uttar Pradesh districts
    {
        id: 148,
        name: "Agra",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 149,
        name: "Aligarh",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 150,
        name: "Ambedkar Nagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 151,
        name: "Amethi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 152,
        name: "Amroha",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 153,
        name: "Auraiya",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 154,
        name: "Ayodhya",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 155,
        name: "Azamgarh",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 156,
        name: "Baghpat",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 157,
        name: "Bahraich",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 158,
        name: "Ballia",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 159,
        name: "Balrampur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 160,
        name: "Banda",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 161,
        name: "Bara Banki",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 162,
        name: "Bareilly",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 163,
        name: "Basti",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 164,
        name: "Bhadohi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 165,
        name: "Bijnor",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 166,
        name: "Budaun",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 167,
        name: "Bulandshahr",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 168,
        name: "Chandauli",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 169,
        name: "Chitrakoot",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 170,
        name: "Deoria",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 171,
        name: "Etah",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 172,
        name: "Etawah",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 173,
        name: "Farrukhabad",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 174,
        name: "Fatehpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 175,
        name: "Firozabad",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 176,
        name: "Gautam Buddha Nagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 177,
        name: "Ghaziabad",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 178,
        name: "Ghazipur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 179,
        name: "Gonda",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 180,
        name: "Gorakhpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 181,
        name: "Hamirpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 182,
        name: "Hapur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 183,
        name: "Hardoi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 184,
        name: "Hathras",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 185,
        name: "Jalaun",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 186,
        name: "Jaunpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 187,
        name: "Jhansi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 188,
        name: "Kannauj",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 189,
        name: "Kanpur Dehat",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 190,
        name: "Kanpur Nagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 191,
        name: "Kasganj",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 192,
        name: "Kaushambi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 193,
        name: "Kheri",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 194,
        name: "Kushinagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 195,
        name: "Lalitpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 196,
        name: "Lucknow",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 197,
        name: "Mahoba",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 198,
        name: "Mahrajganj",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 199,
        name: "Mainpuri",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 200,
        name: "Mathura",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 201,
        name: "Mau",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 202,
        name: "Meerut",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 203,
        name: "Mirzapur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 204,
        name: "Moradabad",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 205,
        name: "Muzaffarnagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 206,
        name: "Pilibhit",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 207,
        name: "Pratapgarh",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 208,
        name: "Prayagraj",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 209,
        name: "Rae Bareli",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 210,
        name: "Rampur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 211,
        name: "Saharanpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 212,
        name: "Sambhal",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 213,
        name: "Sant Kabir Nagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 214,
        name: "Shahjahanpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 215,
        name: "Shamli",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 216,
        name: "Shrawasti",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 217,
        name: "Siddharthnagar",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 218,
        name: "Sitapur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 219,
        name: "Sonbhadra",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 220,
        name: "Sultanpur",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 221,
        name: "Unnao",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 222,
        name: "Varanasi",
        state_id: 26,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 223,
        name: "Araria",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 224,
        name: "Arwal",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 225,
        name: "Aurangabad",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 226,
        name: "Banka",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 227,
        name: "Begusarai",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 228,
        name: "Bhagalpur",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 229,
        name: "Bhojpur",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 230,
        name: "Buxar",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 231,
        name: "Darbhanga",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 232,
        name: "Gaya",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 233,
        name: "Gopalganj",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 234,
        name: "Jamui",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 235,
        name: "Jehanabad",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 236,
        name: "Kaimur (Bhabua)",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 237,
        name: "Katihar",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 238,
        name: "Khagaria",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 239,
        name: "Kishanganj",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 240,
        name: "Lakhisarai",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 241,
        name: "Madhepura",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 242,
        name: "Madhubani",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 243,
        name: "Munger",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 244,
        name: "Muzaffarpur",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 245,
        name: "Nalanda",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 246,
        name: "Nawada",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 247,
        name: "Pashchim Champaran",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 248,
        name: "Samastipur",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 249,
        name: "Saran",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 250,
        name: "Sheikhpura",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 251,
        name: "Sheohar",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 252,
        name: "Sitamarhi",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 253,
        name: "Patna",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 254,
        name: "Purbi Champaran",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 255,
        name: "Purnia",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 256,
        name: "Rohtas",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 257,
        name: "Saharsa",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 258,
        name: "Siwan",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 259,
        name: "Supaul",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 260,
        name: "Vaishali",
        state_id: 4,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 261,
        name: "Central Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 262,
        name: "East Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 263,
        name: "New Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 264,
        name: "North Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 265,
        name: "North East Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 266,
        name: "North West Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 267,
        name: "Shahdara",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 268,
        name: "South Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 269,
        name: "South East Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 270,
        name: "South West Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 271,
        name: "West Delhi",
        state_id: 32,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 272,
        name: "Chandigarh",
        state_id: 30,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    {
        id: 273,
        name: "Bagalkote",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 274,
        name: "Ballari",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 275,
        name: "Belagavi",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 276,
        name: "Bengaluru Rural",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 277,
        name: "Bengaluru South",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 278,
        name: "Bengaluru Urban",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 279,
        name: "Bidar",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 280,
        name: "Chamarajanagar",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 281,
        name: "Chikkaballapura",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 282,
        name: "Chikkamagaluru",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 283,
        name: "Chitradurga",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 284,
        name: "Dakshina Kannada",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 285,
        name: "Davanagere",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 286,
        name: "Dharwad",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 287,
        name: "Gadag",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 288,
        name: "Hassan",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 289,
        name: "Haveri",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 290,
        name: "Kalaburagi",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 291,
        name: "Kodagu",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 292,
        name: "Kolar",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 293,
        name: "Koppal",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 294,
        name: "Mandya",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 295,
        name: "Mysuru",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 296,
        name: "Raichur",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 297,
        name: "Shivamogga",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 298,
        name: "Yadgir",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 299,
        name: "Tumakuru",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 300,
        name: "Udupi",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 301,
        name: "Uttara Kannada",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 302,
        name: "Vijayanagara",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 303,
        name: "Vijayapura",
        state_id: 17,
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]