const languages = [
    {
        id: 1,
        name: "Hindi",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "English",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Punjabi",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Marathi",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: "Haryanvi",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: "Bhojpuri",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: "Rajasthani",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: "Tamil",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: "Telugu",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: "Urdu",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: "Kannada",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: "Malayalam",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 13,
        name: "Nepali",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 14,
        name: "Sanskrit",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 15,
        name: "Bengali",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 16,
        name: "Assamese",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
]