const states = [
    {
        id: 1,
        name: "Andhra Pradesh",
        short_name: "AP",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 2,
        name: "Arunachal Pradesh",
        short_name: "AR",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 3,
        name: "Assam",
        short_name: "AS",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 4,
        name: "Bihar",
        short_name: "BR",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 5,
        name: "Chhattisgarh",
        short_name: "CG",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 6,
        name: "Goa",
        short_name: "GA",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 7,
        name: "Gujarat",
        short_name: "GJ",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 8,
        name: "Haryana",
        short_name: "HR",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 9,
        name: "Himachal Pradesh",
        short_name: "HP",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 10,
        name: "Jharkhand",
        short_name: "JH",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 11,
        name: "Karnataka",
        short_name: "KA",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 12,
        name: "Kerala",
        short_name: "KL",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 13,
        name: "Madhya Pradesh",
        short_name: "MP",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 14,
        name: "Maharashtra",
        short_name: "MH",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 15,
        name: "Manipur",
        short_name: "MN",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 16,
        name: "Meghalaya",
        short_name: "ML",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 17,
        name: "Mizoram",
        short_name: "MZ",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 18,
        name: "Nagaland",
        short_name: "NL",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 19,
        name: "Odisha",
        short_name: "OR",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 20,
        name: "Punjab",
        short_name: "PB",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 21,
        name: "Rajasthan",
        short_name: "RJ",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 22,
        name: "Sikkim",
        short_name: "SK",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 23,
        name: "Tamil Nadu",
        short_name: "TN",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 24,
        name: "Telangana",
        short_name: "TG",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 25,
        name: "Tripura",
        short_name: "TR",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 26,
        name: "Uttar Pradesh",
        short_name: "UP",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 27,
        name: "Uttarakhand",
        short_name: "UK",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 28,
        name: "West Bengal",
        short_name: "WB",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 29,
        name: "Andaman and Nicobar Islands",
        short_name: "AN",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 30,
        name: "Chandigarh",
        short_name: "CH",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 31,
        name: "Dadra and Nagar Haveli and Daman and Diu",
        short_name: "DN",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 32,
        name: "Delhi",
        short_name: "DL",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 33,
        name: "Jammu and Kashmir",
        short_name: "JK",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 34,
        name: "Ladakh",
        short_name: "LA",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 35,
        name: "Lakshadweep",
        short_name: "LD",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },
    {
        id: 36,
        name: "Puducherry",
        short_name: "PY",
        is_active: 1,
        createdAt: new Date(),
        updatedAt: new Date(),
    },

    
]